// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jqzzrkebcekbpdmybvsv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impxenpya2ViY2VrYnBkbXlidnN2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxNzIwNjksImV4cCI6MjA2MDc0ODA2OX0.dUMFhIsW0zGHGZSe3blNBH-DsyXq0wh2OU2YbdkS6iA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);